### ISSUE TITLE
Dilengkapi dengan push notifications (tanpa firebase referensi https://nativenotify.com/blog/articles/flutter/flutter-push-notifications-without-firebase-2022.html)

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-mobile#116]

**Comment by apidong** [comment]
app native tetap butuh firebase untuk mode productionnya
https://app.nativenotify.com/in-app-flutter

**Comment by apidong** [comment]
perlu pemecahan issue karena analisis dibutuhkan di banyak tempat.

- [x] Buat table FCM_token dan tambahkan pengaturan untuk konfigurasi ke Cloud Messaging FCM (opensid) https://github.com/OpenSID/OpenSID/issues/7184
- [x] Buat table log Notifikasi (opensid) https://github.com/OpenSID/OpenSID/issues/7185
- [x] Tambahkan Module Kirim API Push notifikasi ke FCM saat Surat dibuat, disetujui, maupun di tolak (Opensid) https://github.com/OpenSID/OpenSID/issues/7186
- [x] Tambahkan Module Register Token personal FCM untuk masing-masing device (API). https://github.com/OpenSID/wiki-opensid-api/issues/13
- [x] Tambahkan Module Register Token saat Login, Verifikasi Login, dan log-out (mobile-admin) https://github.com/OpenSID/wiki-mobile/issues/168.
- [x] Tambahkan Module Kirim API Push notifikasi ke FCM saat Surat dibuat, disetujui, maupun di tolak (API). https://github.com/OpenSID/wiki-opensid-api/issues/12
- [x] Integrasikan FCM dengan Aplikasi Mobile Admin https://github.com/OpenSID/wiki-mobile/issues/167
- [x] https://github.com/OpenSID/opensid-laravel/issues/181
- [x] Tampilkan Jumlah Notifikasi dan halaman daftar notifikasi. https://github.com/OpenSID/wiki-mobile/issues/169
