### ISSUE TITLE
Layanan Desa - Notifikasi dengan Firebase

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-mobile#178]
Kebutuhan di Opensid 

- [x] Buat tabel untuk menampung data token dan log notifikasi https://github.com/OpenSID/OpenSID/issues/7314
- [x] Kirim Notifikasi ke Operator setelah Pemohon selesai mengajukan surat melalui layanan mandiri. https://github.com/OpenSID/OpenSID/issues/7315
- [x] Kirim Notifikasi ke Operator saat surat dibatalakan oleh pemohon melalui layanan mandiri. https://github.com/OpenSID/OpenSID/issues/7426
- [x] Kirim Notifikasi ke Pemohon saat surat sedang diproses https://github.com/OpenSID/OpenSID/issues/7427
- [x] Kirim notifikasi ke Pemohon jika Surat sudah siap diambil https://github.com/OpenSID/OpenSID/issues/7428
- [x] Kirim notifikasi ke Pemohon jika Surat dikembalikan karena Kurang Lengkap dan setelah selesai melengkapi surat https://github.com/OpenSID/OpenSID/issues/7464

Kebutuhan di API

- [x] Modul Registrasi Token Setelah Login dan hapus token setelah login. https://github.com/OpenSID/opensid-laravel/issues/212
- [x] Kirim Notifikasi ke Operator setelah Pemohon selesai mengajukan surat melalui layanan mandiri. https://github.com/OpenSID/opensid-laravel/issues/214
- [x] Buat modul Notifikasi untuk menampilkan log notifikasi, termasuk merubah status read saat pesan notifikasi dibuka. https://github.com/OpenSID/opensid-laravel/issues/218
- [x] Buat API untuk akumulasi Jumlah Notifikasi https://github.com/OpenSID/opensid-laravel/issues/216

Kebutuhan Mobile layanan

- [x] Integrasikan Mobile layanan dengan Firebase Cloud Messaging (FCM) https://github.com/OpenSID/wiki-mobile/issues/182
- [x] Modul Registrasi Token Setelah Login https://github.com/OpenSID/wiki-mobile/issues/188
- [ ] Kirim Notifikasi ke Operator setelah permohon selesai mengajukan surat Melalui API.
- [ ] Tampilan Jumlah notifikasi di halaman beranda
- [ ] Tampilan daftar Notifikasi halaman mobile layanan.
